### ISSUE TITLE
[Task] Verify all apis implemented

### ISSUE THREAD

**Issue by maruTA-bis5** [maruTA-bis5/mattermost4j#177]
Based on: https://github.com/mattermost/mattermost-api-reference/tree/519eaaf96ce39c74123d63eae36d47a2dd0afccf
If missing / wrong api found, create issues to fix it.

### Note
- APIs that can accept Etag are not documented in mattermost-api-reference, but implemented in mattermost-server.
### Check list
- [x] AuditsApi - In api document, audit related apis written in system section.
    - Invalid
        - [x] needless Etag overload: `#getAudits` -> #180
- [x] AuthenticationApi - In api document, `#switchAccountType` in users section.
- [x] BrandApi
- [x] ChannelApi
    - Missing
        - [x] `GET /channels/{channel_id}/timezones` -> #107
        - [x] `PUT /channels/{channel_id}/patch` -> #181
        - [x] `GET /teams/{team_id}/channels/autocomplete` = #182
        - [x] `GET /teams/{team_id}/channels/search_autocomplete` -> #182
        - [x] `#addChannelMembers`: `post_root_id` parameter-> #183
        - [x] `PUT /channels/{channel_id}/members/{user_id}/schemeRoles` -> #201
            - Notice: Mattermost4j does not support scheme based roles currently.
        - [x] `PUT /channels/{channel_id}/scheme` -> #202
    - Invalid
        - [x] needless Etag overloads: except getPinnedPosts and getChannelsForTeamForUser -> #180
- [x] ClusterApi
- [x] CommandsApi
- [x] ComplianceApi
- [x] ElasticsearchApi
- [x] EmojiApi
    - Missing
        - [x] `#getEmojiList`: `sort` parameter -> #184
- [x] FilesApi
    - Missing
        - [x] `#uploadFile`: `client_ids`, `channel_id`(in query), and `filename`(in query) parameters -> #185
- [x] GeneralApi (SystemApi, #117)
    - Missing
        - [x] `POST /file/s3_test` -> #186
        - [x] `GET /config/environment` -> #187
- [x] LdapApi
- [x] LogsApi - In api document, log related apis written in system section.
- [x] OAuthApi
    - Missing
        - [x] `PUT /oauth/apps/{app_id}` -> #58
- [x] PluginApi
- [x] PostApi
    - MIssing
        - [x] `#searchPosts`: `time_zone_offset` and `include_deleted_channels` parameters. -> #188
        - [x] `POST /posts/{post_id}/actions/{action_id}` -> #110
            - Notice: Mattermost4j does not support post action currently.
    - Concern
        - [x] Deprecate `#updatePost(String, Post)` API to removal. Use `#updatePost(Post)` instead. -> #189
- [x] PreferencesApi
- [x] ReactionApi
    - Missing
         - [x] `POST /posts/ids/reactions` -> #156
- [x] SamlApi
    - Concern
        - [x] Rename `#{upload,remove}SamlPrivateCertificate` to `#{upload,remove}SamlPrivateKey` -> #190
- [x] StatusApi
    - Invalid
        - [x] needless Etag overload: `#getUserStatus` -> #180
- [x] TeamApi
    - Missing
        - [x] `PUT /teams/{team_id}/members/{user_id}/schemeRoles` -> #201
            - Notice: Mattermost4j does not support scheme based roles currently.
        - [x] `DELETE /teams/invites/email` -> #191
        - [x] `PUT /teams/{team_id}/scheme` -> #202
            - Notice: Mattermost4j does not support scheme based roles currently.
    - Invalid
        - [x] needless Etag overload: all apis -> #180
        - [x] missing Etag overload: `#getTeamIcon` -> #192
        - [x] test `TeamsApiTest#addUserToTeamFromInvite` is marked ignore and may be invalid api call. -> #193
        - [x] `GET /users/{user_id}/teams/unread` is defined as `UserApi#getTeamUnreadForUser`. Move to TeamApi. -> #194
- [x] UserApi
    - Missing
        - [x] `#searchUsers`, `#autocompleteUsers`, `#autocompleteUsersInChannel`, `#autocompleteUsersInTeam`: `limit` parameter -> #195
        - [x] `GET /users/stats` -> #196
        - [x] `GET /users/{user_id}/image/default`  -> #197
        - [x] `PUT /users/{user_id}/auth` -> #70
        - [x] `POST /users/{user_id}terms_of_service` -> #203
        - [x] `GET /users/{user_id}terms_of_service` -> #203
    - Invalid
        - [x] needless Etag overload: `#autocompleteUsers`, `#autocompleteUsersInChannel`, `#autocompleteUsersInTeam`, `#getMe`, `#getSessions`, `#getUser`, `#getUserAudits`, `#getUserByEmail`, `#getUserByUsername`, `#getUsers`, `#getUsersInChannel`. `#getUsersInTeam`, `#getUsersNotInChannel`, `#getUsersNotInTeam`, and `#getUsersWithoutTeam`. -> #180
    - Concern
        - [x] Rename parameter to same as mattermost api doc: `UserApi#resetPassword`: `token` to `code` -> #198
- [x] WebhookApi
    - Invalid
        - [x] needless Etag overload: All api -> #180
- [x] WebrtcApi - Already removed from api-doc (#94).
- [x] others
    - Missing
        - [x] actions.yaml -> #110
        - [x] dataretention.yaml -> #59
        - [x] groups.yaml (LDAP groups) -> #199
        - [x] jobs.yaml -> #34 
        - [x] opengraph.yaml -> #200
        - [x] roles.yaml -> #201
        - [x] schemes.yaml -> #202
        - [x] service_terms.yaml -> #203
    - [x] Verify and update description: correct Pager parameter usage? -> #179
        - For example, `GET /users/{user_id}/audits` accept `page`/`per_page` parameters, but not explained in api documentation (this is document's bug).

**Comment by maruTA-bis5** [comment]
All sub tasks are converted to issues.
